apiVersion: v1
kind: Secret
metadata:
    name: mealie-cnpg-user-secret
    annotations:
        replicator.v1.mittwald.de/replicate-to: monitoring-system,cnpg-system,automation
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:VL0sdiiWuA/80RPlJn5JT3UTm31VWzeA,iv:gukBzMyP6sJg7IgBxIQHBegFSmQQwvlqKK/Hur2tW2Q=,tag:GFKayxNU97tso9ZTHZWu+g==,type:str]
    password: ENC[AES256_GCM,data:hQMJUzfIqLlGT0TujV3fB3K0EXpCeq2sXaPhSA==,iv:3mDE4zetojhufVR6+YPOYFfO26PUQDKwKgLdr8j6KKQ=,tag:Mu7romWbgT+KZe7PjD2MmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109fzapgarv59gpyu5tgmwgn7j3hwmfs0dhrz3lrqvjy046jxafnse30kvj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWU81Q3RnbEp3Wnd4SklU
            YmNkNG0rUzNicWtRNjZwMFdnMDhuYlNoUlhvCnFoTGh6VnRyMEREdkNsMHJQTW9G
            K3lEZlZGSVFnRGZwYUozRmRWV1ZoQjQKLS0tIElJN0h6eUhyS3ZkVFRrajNuUXd4
            L0JsUHZCVmNGZG5nR2xTdW1pTnJEazAKWZ7MxSLehXVc504xsHrSOiQe8eJbwV4c
            Odv1LJtbSlozkM1my0rTXtemgj7d81GOQzBZ2+xbXz6O0mnsc86gOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-25T13:53:01Z"
    mac: ENC[AES256_GCM,data:/VouF8k570666FMwgAQxu1l8oH6yHrWP7ym2CANEEPNAMvGkpqeeSOoqYzrrrCzXM5TS7VpfzcP9uAvoYswQ4ImTCGyF81ksB7O/gO9WDd3o6TO2NRLyqDKNJQPiuNwR55NbpOLIxfNMTCBWUmoXOVlB0OdClUTOrsc7jCxZxMw=,iv:3RJx16Ko4hWAqyKunDZOBEVUuh6HNafnxRvaCJsFf3o=,tag:p+l8rT7Ov6aPq69BNEH2WA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.9.2
